import { Emoji } from 'enums'

export const emoji: Record<Emoji, Array<string>> = {
  calendar: [':calendar:', '\ud83d\udcc6'],
  partyingFace: [':partying_face:', '\ud83e\udd73'],
  uncensoredFace: [':face_with_symbols_on_mouth:', '\ud83e\udd2c'],
  neutralFace: [':neutral_face:', '\ud83d\ude10'],
  technologist: [':technologist:', '\ud83e\uddd1\u200d\ud83d\udcbb'],
  elevator: [':elevator:', '\ud83d\uded7'],
  door: [':door:', '\ud83d\udeaa'],
  moyai: [':moyai:', '\ud83d\uddff'],
  clock: [':clock1:', '\ud83d\udd50'],
  computer: [':computer:', '\ud83d\udcbb'],
  iphone: [':iphone:', '\ud83d\udcf1'],
  pager: [':pager:', '\ud83d\udcdf'],
  zap: [':zap:', '\u26a1\ufe0f'],
  telephoneReceiver: [':telephone_receiver:', '\ud83d\udcde'],
  briefcase: [':briefcase:', '\ud83d\udcbc'],
  chart: [':chart_with_upwards_trend:', '\ud83d\udcc8'],
  wheelchair: [':man_in_manual_wheelchair:', '\ud83d\udc68\u200d\ud83e\uddbd'],
  horns: [':the_horns:', '\ud83e\udd18'],
  medal: [':sports_medal:', '\ud83e\udd47'],
  radio: [':radio:', '\ud83d\udcfb'],
  notFound: [':x:', '\u274c'],
  defaultFlag: [':flags:', '\ud83c\udf8f'],
  usFlag: [':flag-us:', '\ud83c\uddfa\ud83c\uddf8'],
  inFlag: [':flag-in:', '\ud83c\uddee\ud83c\uddf3'],
  ruFlag: [':flag-ru:', '\ud83c\uddf7\ud83c\uddfa'],
  kgFlag: [':flag-kg:', '\ud83c\uddf0\ud83c\uddec'],
  uaFlag: [':flag-ua:', '\ud83c\uddfa\ud83c\udde6'],
  ukFlag: [':flag-uk:', '\ud83c\uddec\ud83c\udde7'],
  cnFlag: [':flag-cn:', '\ud83c\udde8\ud83c\uddf3'],
  deFlag: [':flag-de:', '\ud83c\udde9\ud83c\uddea'],
  frFlag: [':flag-fr:', '\ud83c\uddeb\ud83c\uddf7'],
  jpFlag: [':flag-jp:', '\ud83c\uddef\ud83c\uddf5'],
}
