name: Release CI

on:
  push:
    branches:
      - MR2362

jobs:
  main:
    name: NPM Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16


      - name: Install dependencies
        run: yarn install

      - name: Build package
        run: yarn build


      - name: Release new version to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.SECRETS_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release


