name: Release CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.SECRETS_GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          DEPLOY_DIR: my/deploy/dir
          SRC_PACKAGE_DIR: my/src/package

